// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: candlestick.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamCandlesticksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Symbol to stream (e.g., "BTCUSDT")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCandlesticksRequest) Reset() {
	*x = StreamCandlesticksRequest{}
	mi := &file_candlestick_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCandlesticksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCandlesticksRequest) ProtoMessage() {}

func (x *StreamCandlesticksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candlestick_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCandlesticksRequest.ProtoReflect.Descriptor instead.
func (*StreamCandlesticksRequest) Descriptor() ([]byte, []int) {
	return file_candlestick_proto_rawDescGZIP(), []int{0}
}

func (x *StreamCandlesticksRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Candlestick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Open          string                 `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candlestick) Reset() {
	*x = Candlestick{}
	mi := &file_candlestick_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candlestick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candlestick) ProtoMessage() {}

func (x *Candlestick) ProtoReflect() protoreflect.Message {
	mi := &file_candlestick_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candlestick.ProtoReflect.Descriptor instead.
func (*Candlestick) Descriptor() ([]byte, []int) {
	return file_candlestick_proto_rawDescGZIP(), []int{1}
}

func (x *Candlestick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candlestick) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Candlestick) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Candlestick) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Candlestick) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Candlestick) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Candlestick) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_candlestick_proto protoreflect.FileDescriptor

var file_candlestick_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b,
	0x22, 0x33, 0x0a, 0x19, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xab, 0x01, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x65,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x32, 0x6e, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69,
	0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x12, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x73, 0x12,
	0x26, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x74, 0x69, 0x63, 0x6b, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63,
	0x6b, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x62, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x74, 0x72,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_candlestick_proto_rawDescOnce sync.Once
	file_candlestick_proto_rawDescData = file_candlestick_proto_rawDesc
)

func file_candlestick_proto_rawDescGZIP() []byte {
	file_candlestick_proto_rawDescOnce.Do(func() {
		file_candlestick_proto_rawDescData = protoimpl.X.CompressGZIP(file_candlestick_proto_rawDescData)
	})
	return file_candlestick_proto_rawDescData
}

var file_candlestick_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_candlestick_proto_goTypes = []any{
	(*StreamCandlesticksRequest)(nil), // 0: candlestick.StreamCandlesticksRequest
	(*Candlestick)(nil),               // 1: candlestick.Candlestick
}
var file_candlestick_proto_depIdxs = []int32{
	0, // 0: candlestick.CandlestickService.StreamCandlesticks:input_type -> candlestick.StreamCandlesticksRequest
	1, // 1: candlestick.CandlestickService.StreamCandlesticks:output_type -> candlestick.Candlestick
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_candlestick_proto_init() }
func file_candlestick_proto_init() {
	if File_candlestick_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_candlestick_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_candlestick_proto_goTypes,
		DependencyIndexes: file_candlestick_proto_depIdxs,
		MessageInfos:      file_candlestick_proto_msgTypes,
	}.Build()
	File_candlestick_proto = out.File
	file_candlestick_proto_rawDesc = nil
	file_candlestick_proto_goTypes = nil
	file_candlestick_proto_depIdxs = nil
}
